#!/usr/bin/env python3
"""Generate portable IEEE CRC-32 slicing-by-eight tables (PNG polynomial)."""
from pathlib import Path

first = []
for value in range(256):
    for _ in range(8):
        value = (value >> 1) ^ (0xedb88320 if value & 1 else 0)
    first.append(value)
tables = [first]
for _ in range(7):
    tables.append([(value >> 8) ^ first[value & 255] for value in tables[-1]])
lines = ['/* Generated by scripts/generate-crc32.py; IEEE CRC-32, not CRC-32C. */',
         '#ifndef TERMSHOT_CRC32_TABLE_H', '#define TERMSHOT_CRC32_TABLE_H',
         '#include <stdint.h>', 'static const uint32_t crc32_table[8][256] = {']
for table in tables:
    lines.append('    {')
    for offset in range(0, 256, 8):
        lines.append('        ' + ', '.join(f'0x{value:08x}' for value in table[offset:offset+8]) + ',')
    lines.append('    },')
lines.extend(['};', '#endif', ''])
(Path(__file__).resolve().parents[1] / 'src/crc32_table.h').write_text('\n'.join(lines))
