//! Writes src/crc32_table.h: the IEEE CRC-32 (PNG's polynomial, not
//! CRC-32C) slicing-by-eight tables that src/png_crc.h reads.
//!
//!     tools/crc32-table.sh                 # rewrites src/crc32_table.h
//!     target/crc32-table > FILE            # what test.sh compares

fn main() {
    let mut tables = [[0u32; 256]; 8];
    for (i, entry) in tables[0].iter_mut().enumerate() {
        let mut value = i as u32;
        for _ in 0..8 {
            value = (value >> 1) ^ if value & 1 != 0 { 0xedb8_8320 } else { 0 };
        }
        *entry = value;
    }
    // Each table consumes another byte of the recurrence.
    for t in 1..8 {
        for i in 0..256 {
            let previous = tables[t - 1][i];
            tables[t][i] = (previous >> 8) ^ tables[0][(previous & 255) as usize];
        }
    }
    let mut out = String::from(
        "/* Generated by tools/crc32-table.rs; IEEE CRC-32, not CRC-32C. */\n\
         #ifndef TERMSHOT_CRC32_TABLE_H\n#define TERMSHOT_CRC32_TABLE_H\n\
         #include <stdint.h>\nstatic const uint32_t crc32_table[8][256] = {\n",
    );
    for table in &tables {
        out.push_str("    {\n");
        for row in table.chunks(8) {
            let row: Vec<String> = row.iter().map(|value| format!("0x{value:08x}")).collect();
            out.push_str(&format!("        {},\n", row.join(", ")));
        }
        out.push_str("    },\n");
    }
    out.push_str("};\n#endif\n");
    print!("{out}");
}
