#!/bin/sh
# Regenerate src/rowcolumn_diacritics.rs, the diacritics a kitty Unicode
# placeholder (U+10EEEE) gives its row, column and image id's high byte
# with, from kitty's gen/rowcolumn-diacritics.txt. The n-th code point in that
# file (from 0) stands for n; kitty's diacritic_to_num returns n + 1.
#
#   tools/rowcolumn-diacritics.sh [kitty revision]
set -eu
cd "$(dirname "$0")/.."
revision=${1:-9939c7b4711233a048f21245b3963f9f84120f4c}
src=target/rowcolumn-diacritics-$revision.txt
mkdir -p target
[ -f "$src" ] || curl -fsS -o "$src" \
    "https://raw.githubusercontent.com/kovidgoyal/kitty/$revision/gen/rowcolumn-diacritics.txt"
awk -F';' -v revision="$revision" '
    /^#/ || NF == 0 { next }
    {
        value = 0
        for (i = 1; i <= length($1); i++)
            value = value * 16 + index("0123456789ABCDEF", substr($1, i, 1)) - 1
        if (n > 0 && value <= last) { print "not ascending at " $1 | "cat 1>&2"; exit 1 }
        last = value
        codes[n++] = $1
    }
    END {
        print "// Generated by tools/rowcolumn-diacritics.sh from kitty " revision ","
        print "// gen/rowcolumn-diacritics.txt. Do not edit."
        print ""
        print "/// The row and column diacritics of a kitty Unicode placeholder, ascending:"
        print "/// the one at index n stands for n."
        printf "pub static DIACRITICS: [u32; %d] = [", n
        for (i = 0; i < n; i++) {
            if (i % 10 == 0) printf "\n   "
            printf " 0x%s,", codes[i]
        }
        print "\n];"
    }
' "$src" > src/rowcolumn_diacritics.rs
echo "wrote src/rowcolumn_diacritics.rs from kitty $revision"
