//! Generate src/unicode_tables.rs from the Unicode Character Database.
//! Run tools/unicode-tables.sh, which downloads the files and runs this.
//!
//!   unicode-tables <ucd dir> <version> > src/unicode_tables.rs
//!
//! Widths follow wcwidth as terminals use it:
//! - 0: nonspacing and enclosing marks (Mn, Me), format characters (Cf)
//!   except U+00AD SOFT HYPHEN, and Hangul Jamo medial vowels and finals
//!   (U+1160..U+11FF, U+D7B0..U+D7FF);
//! - 2: East Asian Wide or Fullwidth (W, F), or Emoji_Presentation;
//! - 1: everything else.
//!
//! Canonical compositions are the two-code-point canonical decompositions
//! in UnicodeData.txt, minus Full_Composition_Exclusion.

use std::collections::BTreeSet;
use std::fs;

fn hex(s: &str) -> u32 {
    u32::from_str_radix(s.trim(), 16).unwrap_or_else(|_| panic!("bad code point {s:?}"))
}

/// "0041" or "0041..005A" -> (first, last).
fn range(s: &str) -> (u32, u32) {
    match s.trim().split_once("..") {
        Some((a, b)) => (hex(a), hex(b)),
        None => (hex(s), hex(s)),
    }
}

/// Lines of a UCD property file as (range, value), comments dropped.
fn property_lines(text: &str) -> impl Iterator<Item = ((u32, u32), String)> + '_ {
    text.lines().filter_map(|line| {
        let line = line.split('#').next().unwrap().trim();
        let (cps, value) = line.split_once(';')?;
        Some((range(cps), value.trim().to_string()))
    })
}

/// Merge a set of code points into sorted, non-overlapping ranges.
fn ranges(set: &BTreeSet<u32>) -> Vec<(u32, u32)> {
    let mut out: Vec<(u32, u32)> = Vec::new();
    for &cp in set {
        match out.last_mut() {
            Some((_, last)) if *last + 1 == cp => *last = cp,
            _ => out.push((cp, cp)),
        }
    }
    out
}

fn print_ranges(name: &str, doc: &str, set: &BTreeSet<u32>) {
    let rs = ranges(set);
    println!("/// {doc}");
    println!("pub static {name}: [(u32, u32); {}] = [", rs.len());
    for chunk in rs.chunks(6) {
        let row: Vec<String> = chunk.iter().map(|(a, b)| format!("(0x{a:04X}, 0x{b:04X})")).collect();
        println!("    {},", row.join(", "));
    }
    println!("];");
    println!();
}

fn main() {
    let args: Vec<String> = std::env::args().collect();
    let (dir, version) = (&args[1], &args[2]);
    let read = |name: &str| fs::read_to_string(format!("{dir}/{name}")).unwrap_or_else(|e| panic!("{name}: {e}"));

    let mut zero = BTreeSet::new();
    let mut decompositions = Vec::new();
    for line in read("UnicodeData.txt").lines() {
        let fields: Vec<&str> = line.split(';').collect();
        let cp = hex(fields[0]);
        if matches!(fields[2], "Mn" | "Me" | "Cf") && cp != 0x00AD {
            zero.insert(cp);
        }
        let parts: Vec<&str> = fields[5].split_whitespace().collect();
        if parts.len() == 2 && !parts[0].starts_with('<') {
            decompositions.push((hex(parts[0]), hex(parts[1]), cp));
        }
    }
    zero.extend(0x1160..=0x11FF);
    zero.extend(0xD7B0..=0xD7FF);

    let mut wide = BTreeSet::new();
    for ((a, b), value) in property_lines(&read("EastAsianWidth.txt")) {
        if value == "W" || value == "F" {
            wide.extend(a..=b);
        }
    }
    for ((a, b), value) in property_lines(&read("emoji-data.txt")) {
        if value == "Emoji_Presentation" {
            wide.extend(a..=b);
        }
    }
    // A combining mark in a wide block (U+302A..U+302D) is still zero width.
    wide.retain(|cp| !zero.contains(cp));

    let mut excluded = BTreeSet::new();
    for ((a, b), value) in property_lines(&read("DerivedNormalizationProps.txt")) {
        if value == "Full_Composition_Exclusion" {
            excluded.extend(a..=b);
        }
    }
    let mut compose: Vec<(u32, u32, u32)> = decompositions.into_iter().filter(|(_, _, c)| !excluded.contains(c)).collect();
    compose.sort();

    println!("// Generated by tools/unicode-tables.sh from Unicode {version}. Do not edit.");
    println!();
    print_ranges("ZERO_WIDTH", "Code points that take no cell.", &zero);
    print_ranges("DOUBLE_WIDTH", "Code points that take two cells.", &wide);
    println!("/// Canonical compositions (base, mark, composed), sorted by base then mark.");
    println!("pub static COMPOSE: [(u32, u32, u32); {}] = [", compose.len());
    for chunk in compose.chunks(4) {
        let row: Vec<String> = chunk.iter().map(|(a, b, c)| format!("(0x{a:04X}, 0x{b:04X}, 0x{c:04X})")).collect();
        println!("    {},", row.join(", "));
    }
    println!("];");
}
